# کانفیگ یاب حرفه‌ای - Docker Compose Configuration
version: '3.8'

services:
  config-finder:
    build: .
    container_name: config-finder-app
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - config-finder-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis برای کش (اختیاری - برای آینده)
  redis:
    image: redis:7-alpine
    container_name: config-finder-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - config-finder-network
    profiles:
      - with-redis

  # Nginx Reverse Proxy (اختیاری)
  nginx:
    image: nginx:alpine
    container_name: config-finder-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - config-finder
    restart: unless-stopped
    networks:
      - config-finder-network
    profiles:
      - with-nginx

volumes:
  redis_data:
    driver: local

networks:
  config-finder-network:
    driver: bridge

# اجرای حالت‌های مختلف:
# 
# فقط اپلیکیشن اصلی:
# docker-compose up -d
#
# با Redis:
# docker-compose --profile with-redis up -d
#
# با Nginx:
# docker-compose --profile with-nginx up -d
#
# همه سرویس‌ها:
# docker-compose --profile with-redis --profile with-nginx up -d
